### ISSUE TITLE
chapter_6.md 428행 오탈자

### ISSUE THREAD

**Issue by DCnomics** [LOPES-HUFS/SQL#2]
최솟값을 구해주는 명령어 `MIN`과 최댓값을 구해주는 명령어인 `MAX`도 위의 연산 명령어들과 동일하다. 아래의 코드를 입력하고 결과를 확인해보자.

**Comment by dialektike** [comment]
수정 완료
https://github.com/LOPES-HUFS/SQL/commit/3d1f1f4b25a9298fd5c8e4c8fd4fd8be3ebe194b
